# Dongle config
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# ▼ この1行を追加して、左右両方（2台）を接続できるようにします
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

# Pointing config
CONFIG_ZMK_POINTING=y

# Display config
CONFIG_ZMK_DISPLAY=y
CONFIG_XIAORD_BG_1=y
