CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_BT_MAX_CONN=7
CONFIG_BT_MAX_PAIRED=7
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_DISPLAY=y
CONFIG_XIAORD_BG_1=y
CONFIG_ZMK_SPLIT=y
