CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_BT_MAX_CONN=7
CONFIG_BT_MAX_PAIRED=7
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_DISPLAY=y
CONFIG_XIAORD_BG_1=y
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
# システムと通信の処理用メモリ（スタックサイズ）を倍増させてフリーズを防ぐ
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
CONFIG_MAIN_STACK_SIZE=4096
# ダミー枠のドライバを有効化（__device_dts_ord エラーを防止）
CONFIG_KSCAN_MOCK=y
# 分割機能を確実に有効化
CONFIG_ZMK_SPLIT=y
